- name: Pull down trellnotes repo
  become_user: "{{ user }}"
  git:
    repo: 'https://github.com/himmAllRight/curse-rue.git'
    dest: "/home/{{ user }}/Documents/Programming/python/curse-rue"
    clone: yes
    update: no
    recursive: no
  tags:
    - python
    - curse-rue
