---
- name: Setup a DO Droplet
  hosts: digitalocean
  vars:
    do_token: 'default_api_key'
    droplet:
    droplet_name: 'droplet_name'
    droplet_region: 'NYC3'
    droplet_size: '1G'


  tasks:
    - name: Check that do_token API Key is set.
      fail:
        msg: "do_token api key not set."
      when:
        - do_token|lower  == 'default_api_key'

    - name: Print out API key var
      debug:
        msg: "Hello {{ ansible_user }}. DO Key: {{ do_token }}!"

    - name: Check that droplet_name set.
      fail:
        msg: "droplet_name not set."
      when:
        - droplet_name|lower  == 'droplet_name'

