- name: Pull down dotfiles repo
  become_user: "{{ user }}"
  git:
    repo: 'https://github.com/himmAllRight/dotfiles.git'
    dest: "/home/{{ user }}/dotfiles"
    clone: yes
    update: no
    recursive: no

