- name: Set global git name
  become_user: ryan
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  when: git_name is defined


- name: Set global git email
  become_user: ryan
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  when: git_email is defined

- name: Set global git editor
  become_user: ryan
  git_config:
    name: core.editor
    scope: global
    value: "{{ git_editor }}"
  when: git_editor is defined
