- name: Ensure Documents dir exists [for scripts subdir]
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/Documents"
    state: directory

- name: Pull down scripts repo
  become_user: "{{ user }}"
  git:
    repo: 'https://github.com/himmAllRight/scripts.git'
    dest: "/home/{{ user }}/Documents/scripts"
    clone: yes
