- name: Ensure Builds dir exists
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/Builds"
    state: directory


- name: Pull down ry-org-scrum repo
  become_user: "{{ user }}"
  git:
    repo: 'https://github.com/himmAllRight/ry-org-scrum.git'
    dest: "/home/{{ user }}/Builds/ry-org-scrum"
    clone: yes
    update: no
    recursive: no
