- name: Add desired groups first
  group:
    name: "{{ item }}"
    state: present
  # loop: "{{ groups }}"
  # Can't get this to work with vars...
  loop:
    - wheel
    - sudo
    - docker
    - kvm
    - libvirt
    - lxd

- name: Adding ryan user
  when: add_user is defined
  user:
    name: "{{ add_user }}"
    comment: Ryan
    shell: /bin/bash
    groups: wheel,sudo,docker,lxd,docker,kvm,libvirt
    append: yes

