- name: Add desired groups first
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ add_groups }}"

- name: "Adding user {{ add_user }}"
  when: add_user is defined
  user:
    name: "{{ add_user }}"
    shell: /bin/bash
    groups: "{{ add_user_groups }}"
    append: yes

