---
add_list:
  # Core
  - fish
  - git
  - htop
  - nmon
  - ncdu
  - pass
  - stow
  - tmux
  - vim
  - zsh

  # Dev
  - python3
  - python36
  - npm
  - python2-flake8
  - python3-flake8
  - golang
  - ruby-devel
  - gcc

  # Virt
  # System
  - ansible
  - ansible-python3
