---
- name: add RPM Fusion repos
  package:
    state: present
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-29.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-29.noarch.rpm

- name: Update dnf packages
  dnf:
    name: "*"
    state: latest

- include_vars: fedora_packages.yml

- name: Install Fedora  Package List
  dnf: name={{ add_list }}
  register: install_result

- name: Remove Fedora Package List
  dnf:
    name: "{{ remove_list }}"
    state: absent
  register: remove_result
