---
- name: Get Fedora Version
  debug:
    msg: "{{ ansible_distribution }} Version: {{ fedora_version }}"

- name: add RPM Fusion repos
  package:
    state: present
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
  tags:
    - rpmfusion

- name: Update dnf packages
  dnf:
    name: "*"
    state: latest
  tags:
    - dnf

- include_vars: fedora_packages.yml

- name: Install Fedora  Package List
  when: add_list is defined and add_list is not none
  dnf: name={{ add_list }}
  register: install_result
  tags:
    - dnf

- name: Remove Fedora Package List
  when: remove_list is defined and remove_list is not none
  dnf:
    name: "{{ remove_list }}"
    state: absent
  register: remove_result
  tags:
    - dnf
