---
- name: Add desired groups first
  when: add_user_groups is defined and add_user_groups is not none
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ add_user_groups }}"

- name: "Adding user {{ add_user }}"
  when: add_user is defined and add_user_groups is not defined
  user:
    name: "{{ add_user }}"
    shell: /bin/bash
    append: yes

- name: "Adding groups to user {{ add_user }}"
  when: add_user is defined and add_user_groups is defined and add_user_groups is not none
  user:
    name: "{{ add_user }}"
    groups: "{{ add_user_groups }}"
    shell: /bin/bash
    append: yes
