---
- name: Set up Ryan's Fedora Workstation Configuration
  hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    add_user: "ryan"
    user: "ryan"
    git_name: "Ryan Himmelwright"
    git_email: "ryan.himmelwright@gmail.com"
    git_editor: "vim"

  roles:
    - system/fedora-workstation
    - system/base
    - apps/git
    - apps/dotfiles
    - apps/zsh
    - apps/scripts
    - apps/ry-org-scrum
    - apps/website
